INSERT INTO town (id, name) VALUES
    (RANDOM_UUID(), 'Warsaw'),
    (RANDOM_UUID(), 'Krakow'),
    (RANDOM_UUID(), 'Gdansk'),
    (RANDOM_UUID(), 'Wroclaw'),
    (RANDOM_UUID(), 'Poznan'),
    (RANDOM_UUID(), 'Lodz'),
    (RANDOM_UUID(), 'Szczecin'),
    (RANDOM_UUID(), 'Bydgoszcz'),
    (RANDOM_UUID(), 'Lublin'),
    (RANDOM_UUID(), 'Katowice');

INSERT INTO keyword (id, keyword_value) VALUES
    (RANDOM_UUID(), 'food'),
    (RANDOM_UUID(), 'clothing'),
    (RANDOM_UUID(), 'electronics'),
    (RANDOM_UUID(), 'furniture'),
    (RANDOM_UUID(), 'toys'),
    (RANDOM_UUID(), 'books'),
    (RANDOM_UUID(), 'sports'),
    (RANDOM_UUID(), 'beauty'),
    (RANDOM_UUID(), 'automotive'),
    (RANDOM_UUID(), 'health'),
    (RANDOM_UUID(), 'garden'),
    (RANDOM_UUID(), 'pet supplies'),
    (RANDOM_UUID(), 'office supplies'),
    (RANDOM_UUID(), 'baby products'),
    (RANDOM_UUID(), 'jewelry'),
    (RANDOM_UUID(), 'music'),
    (RANDOM_UUID(), 'movies'),
    (RANDOM_UUID(), 'video games'),
    (RANDOM_UUID(), 'home decor'),
    (RANDOM_UUID(), 'tools'),
    (RANDOM_UUID(), 'outdoors'),
    (RANDOM_UUID(), 'travel'),
    (RANDOM_UUID(), 'services'),
    (RANDOM_UUID(), 'survival'),
    (RANDOM_UUID(), 'other');